file(GLOB source_locales "${SOURCE_ASSETS}/locales/*.json")
if(NOT source_locales)
    message(FATAL_ERROR "No source locale resources found")
endif()

foreach(source_locale IN LISTS source_locales)
    get_filename_component(locale_name "${source_locale}" NAME)
    set(copied_locale "${BUILT_ASSETS}/locales/${locale_name}")
    if(NOT EXISTS "${copied_locale}")
        message(FATAL_ERROR "Build output is missing ${locale_name}")
    endif()
    file(SHA256 "${source_locale}" source_hash)
    file(SHA256 "${copied_locale}" copied_hash)
    if(NOT source_hash STREQUAL copied_hash)
        message(FATAL_ERROR "Build output has a stale copy of ${locale_name}")
    endif()
endforeach()
